go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt
go run worker.go -C=64B -config=config.txt