// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: all_messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatcherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int32                  `protobuf:"varint,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatcherRequest) Reset() {
	*x = DispatcherRequest{}
	mi := &file_all_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatcherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatcherRequest) ProtoMessage() {}

func (x *DispatcherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_all_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatcherRequest.ProtoReflect.Descriptor instead.
func (*DispatcherRequest) Descriptor() ([]byte, []int) {
	return file_all_messages_proto_rawDescGZIP(), []int{0}
}

func (x *DispatcherRequest) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type DispatcherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int32                  `protobuf:"varint,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	StartingIndex int32                  `protobuf:"varint,2,opt,name=StartingIndex,proto3" json:"StartingIndex,omitempty"`
	EndingIndex   int32                  `protobuf:"varint,3,opt,name=EndingIndex,proto3" json:"EndingIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatcherResponse) Reset() {
	*x = DispatcherResponse{}
	mi := &file_all_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatcherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatcherResponse) ProtoMessage() {}

func (x *DispatcherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_all_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatcherResponse.ProtoReflect.Descriptor instead.
func (*DispatcherResponse) Descriptor() ([]byte, []int) {
	return file_all_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DispatcherResponse) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *DispatcherResponse) GetStartingIndex() int32 {
	if x != nil {
		return x.StartingIndex
	}
	return 0
}

func (x *DispatcherResponse) GetEndingIndex() int32 {
	if x != nil {
		return x.EndingIndex
	}
	return 0
}

type FilesystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartingIndex int32                  `protobuf:"varint,1,opt,name=startingIndex,proto3" json:"startingIndex,omitempty"`
	NBytes        int32                  `protobuf:"varint,2,opt,name=nBytes,proto3" json:"nBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemRequest) Reset() {
	*x = FilesystemRequest{}
	mi := &file_all_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemRequest) ProtoMessage() {}

func (x *FilesystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_all_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemRequest.ProtoReflect.Descriptor instead.
func (*FilesystemRequest) Descriptor() ([]byte, []int) {
	return file_all_messages_proto_rawDescGZIP(), []int{2}
}

func (x *FilesystemRequest) GetStartingIndex() int32 {
	if x != nil {
		return x.StartingIndex
	}
	return 0
}

func (x *FilesystemRequest) GetNBytes() int32 {
	if x != nil {
		return x.NBytes
	}
	return 0
}

type FilesystemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemResponse) Reset() {
	*x = FilesystemResponse{}
	mi := &file_all_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemResponse) ProtoMessage() {}

func (x *FilesystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_all_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemResponse.ProtoReflect.Descriptor instead.
func (*FilesystemResponse) Descriptor() ([]byte, []int) {
	return file_all_messages_proto_rawDescGZIP(), []int{3}
}

func (x *FilesystemResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FilesystemMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemMetadataRequest) Reset() {
	*x = FilesystemMetadataRequest{}
	mi := &file_all_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemMetadataRequest) ProtoMessage() {}

func (x *FilesystemMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_all_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemMetadataRequest.ProtoReflect.Descriptor instead.
func (*FilesystemMetadataRequest) Descriptor() ([]byte, []int) {
	return file_all_messages_proto_rawDescGZIP(), []int{4}
}

func (x *FilesystemMetadataRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type FilesystemMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes    int32                  `protobuf:"varint,1,opt,name=totalBytes,proto3" json:"totalBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemMetadataResponse) Reset() {
	*x = FilesystemMetadataResponse{}
	mi := &file_all_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemMetadataResponse) ProtoMessage() {}

func (x *FilesystemMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_all_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemMetadataResponse.ProtoReflect.Descriptor instead.
func (*FilesystemMetadataResponse) Descriptor() ([]byte, []int) {
	return file_all_messages_proto_rawDescGZIP(), []int{5}
}

func (x *FilesystemMetadataResponse) GetTotalBytes() int32 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type ConsolidatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NPrimes       int32                  `protobuf:"varint,1,opt,name=nPrimes,proto3" json:"nPrimes,omitempty"`
	TimeElapsed   int32                  `protobuf:"varint,2,opt,name=timeElapsed,proto3" json:"timeElapsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolidatorRequest) Reset() {
	*x = ConsolidatorRequest{}
	mi := &file_all_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidatorRequest) ProtoMessage() {}

func (x *ConsolidatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_all_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidatorRequest.ProtoReflect.Descriptor instead.
func (*ConsolidatorRequest) Descriptor() ([]byte, []int) {
	return file_all_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ConsolidatorRequest) GetNPrimes() int32 {
	if x != nil {
		return x.NPrimes
	}
	return 0
}

func (x *ConsolidatorRequest) GetTimeElapsed() int32 {
	if x != nil {
		return x.TimeElapsed
	}
	return 0
}

type ConsolidatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolidatorResponse) Reset() {
	*x = ConsolidatorResponse{}
	mi := &file_all_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidatorResponse) ProtoMessage() {}

func (x *ConsolidatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_all_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidatorResponse.ProtoReflect.Descriptor instead.
func (*ConsolidatorResponse) Descriptor() ([]byte, []int) {
	return file_all_messages_proto_rawDescGZIP(), []int{7}
}

var File_all_messages_proto protoreflect.FileDescriptor

const file_all_messages_proto_rawDesc = "" +
	"\n" +
	"\x12all_messages.proto\")\n" +
	"\x11DispatcherRequest\x12\x14\n" +
	"\x05jobId\x18\x01 \x01(\x05R\x05jobId\"r\n" +
	"\x12DispatcherResponse\x12\x14\n" +
	"\x05JobId\x18\x01 \x01(\x05R\x05JobId\x12$\n" +
	"\rStartingIndex\x18\x02 \x01(\x05R\rStartingIndex\x12 \n" +
	"\vEndingIndex\x18\x03 \x01(\x05R\vEndingIndex\"Q\n" +
	"\x11FilesystemRequest\x12$\n" +
	"\rstartingIndex\x18\x01 \x01(\x05R\rstartingIndex\x12\x16\n" +
	"\x06nBytes\x18\x02 \x01(\x05R\x06nBytes\"(\n" +
	"\x12FilesystemResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"7\n" +
	"\x19FilesystemMetadataRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\"<\n" +
	"\x1aFilesystemMetadataResponse\x12\x1e\n" +
	"\n" +
	"totalBytes\x18\x01 \x01(\x05R\n" +
	"totalBytes\"Q\n" +
	"\x13ConsolidatorRequest\x12\x18\n" +
	"\anPrimes\x18\x01 \x01(\x05R\anPrimes\x12 \n" +
	"\vtimeElapsed\x18\x02 \x01(\x05R\vtimeElapsed\"\x16\n" +
	"\x14ConsolidatorResponse2O\n" +
	"\x11DispatcherService\x12:\n" +
	"\rAcceptRequest\x12\x12.DispatcherRequest\x1a\x13.DispatcherResponse\"\x002\xa3\x01\n" +
	"\x11FilesystemService\x12:\n" +
	"\rAcceptRequest\x12\x12.FilesystemRequest\x1a\x13.FilesystemResponse\"\x00\x12R\n" +
	"\x15AcceptMetadataRequest\x12\x1a.FilesystemMetadataRequest\x1a\x1b.FilesystemMetadataResponse\"\x002U\n" +
	"\x13ConsolidatorService\x12>\n" +
	"\rAcceptRequest\x12\x14.ConsolidatorRequest\x1a\x15.ConsolidatorResponse\"\x00B\fZ\n" +
	"grpc/protob\x06proto3"

var (
	file_all_messages_proto_rawDescOnce sync.Once
	file_all_messages_proto_rawDescData []byte
)

func file_all_messages_proto_rawDescGZIP() []byte {
	file_all_messages_proto_rawDescOnce.Do(func() {
		file_all_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_all_messages_proto_rawDesc), len(file_all_messages_proto_rawDesc)))
	})
	return file_all_messages_proto_rawDescData
}

var file_all_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_all_messages_proto_goTypes = []any{
	(*DispatcherRequest)(nil),          // 0: DispatcherRequest
	(*DispatcherResponse)(nil),         // 1: DispatcherResponse
	(*FilesystemRequest)(nil),          // 2: FilesystemRequest
	(*FilesystemResponse)(nil),         // 3: FilesystemResponse
	(*FilesystemMetadataRequest)(nil),  // 4: FilesystemMetadataRequest
	(*FilesystemMetadataResponse)(nil), // 5: FilesystemMetadataResponse
	(*ConsolidatorRequest)(nil),        // 6: ConsolidatorRequest
	(*ConsolidatorResponse)(nil),       // 7: ConsolidatorResponse
}
var file_all_messages_proto_depIdxs = []int32{
	0, // 0: DispatcherService.AcceptRequest:input_type -> DispatcherRequest
	2, // 1: FilesystemService.AcceptRequest:input_type -> FilesystemRequest
	4, // 2: FilesystemService.AcceptMetadataRequest:input_type -> FilesystemMetadataRequest
	6, // 3: ConsolidatorService.AcceptRequest:input_type -> ConsolidatorRequest
	1, // 4: DispatcherService.AcceptRequest:output_type -> DispatcherResponse
	3, // 5: FilesystemService.AcceptRequest:output_type -> FilesystemResponse
	5, // 6: FilesystemService.AcceptMetadataRequest:output_type -> FilesystemMetadataResponse
	7, // 7: ConsolidatorService.AcceptRequest:output_type -> ConsolidatorResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_all_messages_proto_init() }
func file_all_messages_proto_init() {
	if File_all_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_all_messages_proto_rawDesc), len(file_all_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_all_messages_proto_goTypes,
		DependencyIndexes: file_all_messages_proto_depIdxs,
		MessageInfos:      file_all_messages_proto_msgTypes,
	}.Build()
	File_all_messages_proto = out.File
	file_all_messages_proto_goTypes = nil
	file_all_messages_proto_depIdxs = nil
}
